[package]
name = "aoc-2022-07"
version = "0.1.0"
authors = ["Jalil David Salamé Messina <jalil.salame@tum.de>"]
edition = "2021"

[[bin]]
path = "main.rs"
name = "aoc-2022-07"


[dependencies]
color-eyre.workspace = true
nom.workspace = true
