[package]
name = "aoc-2022-02"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "aoc-2022-02"
path = "main.rs"

[dependencies]
color-eyre.workspace = true
